[Modules] Button for decline validation request and send to user reas…
telefonicaid/fiware-sinfonier pull request #11
Opened 2016-10-25 13:32 UTC by amatosc

[Modules] Button for decline validation request and send to user reason.

2016-10-25 15:42 UTC, fandrod commented on sinfonier-web/app/controllers/Modules.java
> +  public static void decline(String id, Integer versionCode, String message) throws SinfonierException {
This method needs a @Check("ADMIN"). Only superadmin users can execute this action

2016-10-25 15:45 UTC, fandrod commented on sinfonier-web/app/controllers/Modules.java
> +      moduleNotFoundError("Impossible set it to privatize because we can't found the id: ", id);
This isn't the correct message for this action, maybe copy & paste?

2016-10-25 15:48 UTC, fandrod requested changes
Review previous comments

2016-10-26 06:33 UTC, amatosc commented on sinfonier-web/app/controllers/Modules.java
> +  public static void decline(String id, Integer versionCode, String message) throws SinfonierException {
No, any admin that can validate, can decline as well.

2016-10-26 07:31 UTC, ivan11paths approved these changes

2016-10-26 07:39 UTC, fandrod approved these changes

2016-10-26 07:42 UTC, merged