Merge1.0.1
telefonicaid/fiware-sinfonier pull request #16
Opened 2016-10-28 10:58 UTC by demonodojo

2016-10-28 11:21 UTC, fandrod commented on sinfonier-backend-api/tests/data/topologies.json
> +      "properties": {
With last changes on "develop/1.1.0", this attribute must be called "stormProperties" or "topologyProperties"

2016-10-28 11:22 UTC, fandrod commented on sinfonier-backend-api/tests/data/topologies.json
> +      "properties": {
With last changes on "develop/1.1.0", this attribute must be called "stormProperties" or "topologyProperties"

2016-10-28 11:23 UTC, fandrod commented on sinfonier-web/app/controllers/Modules.java
> +import models.module.ModulesContainer;
Duplicated import

2016-10-28 11:32 UTC, fandrod commented on sinfonier-web/test/data/topologies.json
> +      "properties": {}
With last changes on "develop/1.1.0", this attribute must be called "stormProperties" or "topologyProperties"

2016-10-28 11:32 UTC, fandrod commented on sinfonier-web/test/data/topologies.json
> +      "properties": {}
With last changes on "develop/1.1.0", this attribute must be called "stormProperties" or "topologyProperties"

2016-10-28 11:42 UTC, fandrod commented on sinfonier-web/app/views/Drawers/index.html
> +  function regenerateModulesDD() {
This function was moved to drawer.js file

2016-10-28 11:43 UTC, fandrod commented on sinfonier-web/app/views/Drawers/index.html
> +  function adviseTopologyNotSaved(event, form) {
This function was moved to drawer.js file, but with an old implementation

2016-10-31 08:47 UTC, fandrod approved these changes

2016-10-31 09:01 UTC, fandrod approved these changes

2016-10-31 09:04 UTC, amatosc requested changes
check the test of api please.

2016-10-31 10:54 UTC, amatosc approved these changes

2016-10-31 10:56 UTC, merged