New design is coming
telefonicaid/fiware-sinfonier pull request #17
Opened 2016-10-31 08:21 UTC by amatosc

2016-10-31 11:44 UTC, fandrod requested changes
Con el cambio en los estilos, mejora bastante el aspecto de la aplicación, pero se producen los siguientes problemas:
- Se pierde el estilo del elemento activo en la paginación de módulos o topologías, no se sabe en que página se está, el estilo era este en la versión anterior:
  .btn-bezel.active, .btn-bezel.focus, .btn-bezel:active, .btn-bezel:focus {
  background: #fff !important;
  }
- En el editor se pierde el estilo personalizado que hacía que se establezca el padding-right a 0px en la capa principal, para aprovechar todo el ancho de la pantalla.
- Se añade un padding a todos los input[type="text"] del editor. Con el padding-left, la visualización es incorrecta. Con la asignación del font-family, la visualización del typeInvite de los campos del formulario de Propiedades de una Topología es incorrecta.
- El detalle del perfil de usuario no utiliza el ancho completo de la pantalla, queda mal, cambiar a col-lg-12. Igual para el formulario de edición del perfil.

-Los listados de roles y de "Changelog (Admin)" se siguen viendo bastante mal, ya pasaba con la versión anterior de los estilos.

2016-11-10 12:56 UTC, fandrod commented on sinfonier-web/public/javascripts/modules.js
> +      <i class="material-icons pull-right big-icon">group_work</i>
Este cambio no es código JavaScript/JQuery válido. Con él, no cargan las funciones disponibles en el fichero modules.js, y dejan de funcionar múltiples funcionalidades en el detalle y los formularios de alta/modificación de módulos (código fuente en CodeMirror, añadir/quitar campos, librerías, etc.)

2016-11-10 13:03 UTC, fandrod requested changes
En el editor se pierde el estilo personalizado que hacía que se establezca el padding-right a 0px en la capa principal, para aprovechar todo el ancho de la pantalla.

Se añade un padding a todos los input[type="text"] del editor. Con el padding-left, la visualización es incorrecta.

Sobra el título (H1) en la pantalla del editor, cuando no está a pantalla completa.

Tener en cuenta el comentario añadido en modules.js. Si se pretende cambiar los iconos de los tipos de módulos por material icons, hay que pensar que iconos se usan para spouts y drains, los que van en los últimos commits pueden confundir/despistar a usuarios acostumbrados a versiones anteriores de Sinfonier

2016-11-14 09:45 UTC, fandrod reviewed
Después de los últimos ajustes, el rediseño es válido.
Falta por tomar la decisión sobre que hacer con las pantallas propias de Darwin que se han incorporado a Sinfonier y se han ajustado al nuevo diseño. Ante un cambio de versión de Darwin, pueden surgir problemas, si estas pantallas incluyen nueva funcionalidad, que habrá que traspasar a mano a la copia de las mismas que se trasladado a Sinfonier

2016-11-14 10:14 UTC, amatosc commented
Hi all, I think is a good time to review the code for merging. @fandrod @ivan11paths

2016-11-15 09:18 UTC, fandrod approved these changes

2016-11-15 09:32 UTC, merged