Projects I20863
telefonicaid/fiware-sinfonier pull request #25
Opened 2016-11-10 16:19 UTC by demonodojo

2016-11-11 12:44 UTC, fandrod commented on sinfonier-web/app/controllers/BaseController.java
> +	public static Project getCurrentProject() {
Review the indentation

2016-11-11 12:47 UTC, fandrod commented on sinfonier-web/app/controllers/Projects.java
> +	public static void save(Project project) throws SinfonierException {
Review indentation

2016-11-11 12:53 UTC, fandrod commented on sinfonier-web/app/models/project/Project.java
> +	public Project() {
Review indentation

2016-11-11 12:57 UTC, fandrod commented on sinfonier-web/app/models/project/Project.java
> +  public Boolean isRunning() {
Why the method name is "isRunning" if we test if the status is active?

2016-11-14 13:31 UTC, fandrod commented on sinfonier-web/app/views/Projects/index.html
> +				<div id="empty-project" class="row">
Este botón no se muestra centrado en la pantalla.
Revisar la indentación de los tags anidados

2016-11-14 13:37 UTC, fandrod commented on sinfonier-web/app/views/tags/projects/_form.html
> +        pattern="^(([A-Z]+[a-z0-9]*)+)$" title="&{'Projects.form.err.pattern.name'}"
Falta esta cadena i18n en los ficheros messages y messages.es

2016-11-14 13:56 UTC, fandrod commented on sinfonier-web/app/views/tags/projects/_project.html
> +
Añadir la capa para mostrar los datos del autor del proyecto, como se hace en módulos y topologías. Al poder buscar proyectos por datos del creador, queda mal no mostrar estos datos en la ficha de cada proyecto

2016-11-14 14:04 UTC, fandrod commented on sinfonier-web/conf/messages
> +Projects.details.title = New project
Tendría que ser "Projects.new.title". En inglés en el detalle de un proyecto sale ahora algo como esto:
New project 'PrimerProyecto'

2016-11-14 14:07 UTC, fandrod commented on sinfonier-web/conf/messages
> +Projects.btn.use = Work
Quedaría mejor "Use project"

2016-11-14 14:07 UTC, fandrod commented on sinfonier-web/conf/messages.es
> +Projects.btn.use = Trabajar
Quedaría mejor "Usar proyecto"

2016-11-14 14:09 UTC, fandrod commented on sinfonier-web/app/views/Layouts/darwin-control-panel-header.html
> +	              ${ currentProject.getName()}
Incluir un literal por delante del nombre del proyecto, algo como "Proyecto en uso: ", "Project in use: "

2016-11-14 15:59 UTC, fandrod commented on sinfonier-web/app/models/project/Project.java
> +      notDeletedAndSharing.add(new BasicDBObject(FIELD_SHARING, true));
El atributo FIELD_SHARING se usa solo en las búsquedas, pero no se persiste a nivel de objeto. Falta un atributo:
private Boolean sharing;
a nivel de modelo para que al menos al guardar un proyecto se persiste con un valor "false".
Faltarían también los elementos a nivel de pantallas y acciones de controlador que permitan publicar o despublicar un proyecto.

2016-11-14 16:00 UTC, fandrod requested changes
Ver los comentarios en los distintos fichero modificados

2016-11-15 13:01 UTC, fandrod approved these changes

2016-11-15 15:24 UTC, ivan11paths requested changes

2016-11-15 15:24 UTC, ivan11paths commented on sinfonier-web/app/controllers/Topologies.java
> +      	if ("true".equals(Play.configuration.get("projects")) && project != null )
Formatter incorrect

2016-11-15 15:24 UTC, ivan11paths commented on sinfonier-web/app/models/project/Project.java
> +public class Project implements Cloneable {
You don't create functional test for this controller

2016-11-15 15:24 UTC, ivan11paths commented on sinfonier-web/conf/messages
>  Utils.pagination.last = Last
You should review i18n because 'message' file has more lines.

2016-11-28 12:30 UTC, fandrod approved these changes

2016-11-28 13:34 UTC, ivan11paths approved these changes

2016-11-28 13:34 UTC, merged