I21087
telefonicaid/fiware-sinfonier pull request #28
Opened 2016-11-15 09:32 UTC by demonodojo

Topologies monitoring. Extend API #21087

2016-11-15 09:54 UTC, amatosc commented
Please resolve the conflicts before.

2016-11-28 15:41 UTC, fandrod approved these changes
La parte correspondiente al front end la veo correcta

2016-11-28 16:33 UTC, amatosc commented on sinfonier-backend-api/actions/topologies/GetTopologyInfo.py
> +            info = StormUI.getTopologyByName(topology["name"])
Please, use the constants defined in SinfonierConstants.py

2016-11-28 16:34 UTC, amatosc commented on sinfonier-backend-api/actions/topologies/GetTopologyInfo.py
> +                return ResponsesHandler.handle_200(resp, {'id': topology_id, 'log': ''})
Why do you return an exception as 200 code?

2016-11-28 16:40 UTC, amatosc commented on sinfonier-web/public/javascripts/topologies.js
> +	    	  				,res.data.bolts);
Please, use i18n for make it available for the current languages.

2016-11-28 16:40 UTC, amatosc commented on sinfonier-web/public/javascripts/topologies.js
> +	  {
please, use a correct format.

2016-11-28 16:43 UTC, amatosc requested changes
I can't see the test in sinfonier-backend-api and sinfonier-web neither. As well check other comments in the code please.

2016-11-28 16:48 UTC, demonodojo commented on sinfonier-backend-api/actions/topologies/GetTopologyInfo.py
> +                return ResponsesHandler.handle_200(resp, {'id': topology_id, 'log': ''})
This is an error

2016-12-01 08:46 UTC, amatosc commented on sinfonier-web/test/tests/controllers/TopologiesTest.java
> +      e.printStackTrace();
if this exception is caught what will happen?

2016-12-01 08:47 UTC, amatosc commented on sinfonier-web/test/tests/controllers/TopologiesTest.java
> +        e.printStackTrace();
if this exception is caught what will happen? I think that have to raise it.

2016-12-01 08:48 UTC, amatosc reviewed
Please check the comments.

2016-12-01 11:32 UTC, amatosc approved these changes

2016-12-05 13:25 UTC, ajsanchezsanz approved these changes

2016-12-05 13:27 UTC, merged