[Resolves #20437] Now it is possible to reference topology configurat…
telefonicaid/fiware-sinfonier pull request #3
Opened 2016-10-19 09:06 UTC by fandrod

[Resolves #20437] Now it is possible to reference topology configuration from modules fields, using "[$key]" pattern

2016-10-19 10:10 UTC, demonodojo commented on sinfonier-web/app/views/Drawers/index.html
> +
It is better to have javascript in separate files, and put condition using data values of html.

2016-10-19 15:32 UTC, amatosc commented on sinfonier-web/app/models/storm/ParamsValidator.java
> +      return (validateExtraConfKey(key) && validateExtraConfValue(((String) value).trim()));
if value is null then we will get a NullPointerException, check it if it is a string before. And if you have key but params you don't need validate anything else because the format it's incorrect.

2016-10-19 15:41 UTC, fandrod commented on sinfonier-web/app/models/storm/ParamsValidator.java
> +      return (validateExtraConfKey(key) && validateExtraConfValue(((String) value).trim()));
The only actual call to this method is from public boolean validate(TopologyConfig config).
In this method we call parseExtraConfig, that throws an exception if there are a config key without value.
Maybe this method must be private.

2016-10-20 06:35 UTC, amatosc commented on sinfonier-web/app/models/storm/ParamsValidator.java
> +      return (validateExtraConfKey(key) && validateExtraConfValue(((String) value).trim()));
That method raise an Exception but it's not because it return a null, so you should check if the value returned if not null, anywhere, it's a good practice as well. And if you have key but params you don't need validate anything else because the format it's incorrect.

2016-10-20 06:38 UTC, amatosc requested changes
Right now you will accept any extra param, and we cannot allow this.

2016-10-25 09:37 UTC, amatosc submitted a review, later dismissed

2016-10-25 13:53 UTC, amatosc commented on sinfonier-web/app/controllers/Topologies.java
> +      renderJSON(Codes.CODE_404.toGSON());
This never will be executed.

2016-10-25 14:01 UTC, amatosc commented on sinfonier-web/app/controllers/Topologies.java
> +    render();
In the view, you may add some info, because, the only thing that you see is two inputs without any description. I think that could be a little bit confuse.

2016-10-25 14:04 UTC, fandrod commented on sinfonier-web/app/controllers/Topologies.java
> +    render();
We have also detected this need. This will be added on a future commit/pull request

2016-10-25 14:42 UTC, amatosc approved these changes

2016-10-25 14:48 UTC, demonodojo approved these changes

2016-10-25 15:15 UTC, merged