Jquery version vulnerable. #21734
telefonicaid/fiware-sinfonier pull request #37
Opened 2016-12-09 09:19 UTC by amatosc

2016-12-09 10:32 UTC, demonodojo requested changes

2016-12-09 10:32 UTC, demonodojo commented on sinfonier-web/app/views/Layouts/darwin-control-panel-layout.html
> +<script type="text/javascript" src="@{'/public/javascripts/jquery-3.1.1.min.js'}"></script>
jquery datatables must be upgraded too, and all other plugins like jquery datetime
You can configure datatables js and css here:
https://datatables.net/download/index

2016-12-19 11:36 UTC, amatosc commented on sinfonier-web/app/views/Layouts/darwin-control-panel-layout.html
> +<script type="text/javascript" src="@{'/public/javascripts/jquery-3.1.1.min.js'}"></script>
It's compatible with those plugins

2016-12-22 11:05 UTC, demonodojo approved these changes

2016-12-23 07:27 UTC, merged