Export topologies #20435
telefonicaid/fiware-sinfonier pull request #4
Opened 2016-10-19 10:24 UTC by demonodojo

2016-10-19 11:00 UTC, amatosc commented
Do **not** merge to Master!!!

2016-10-19 11:05 UTC, ivan11paths requested changes

2016-10-19 11:05 UTC, ivan11paths commented on sinfonier-web/app/models/module/ModuleVersion.java
> +			Logger.error(e.getMessage());
If an error happens this code only print a log. You should return an error.

2016-10-19 11:05 UTC, ivan11paths commented on sinfonier-web/app/models/responses/Codes.java
>    CODE_400("NOOK", 400),
You can add correct text for all codes.

2016-10-19 14:28 UTC, fandrod approved these changes

2016-10-19 14:43 UTC, amatosc commented on sinfonier-web/app/models/topology/Wire.java
> +  private String xtype;
Why do you need rename it?

2016-10-19 14:48 UTC, amatosc commented on sinfonier-web/app/models/topology/json/serializers/TopologySerializer.java
> +    	try {
Please, formatted correctly

2016-10-19 15:34 UTC, demonodojo commented
Gson uses the name of the field to serialize it in json. We use xtype un
our topologies, so renaming it will do it fine.

On Wed, Oct 19, 2016 at 4:43 PM, Alex Matos <notifications@github.com>
wrote:

> *@amatosc* commented on this pull request.
> ------------------------------
>
> In sinfonier-web/app/models/topology/Wire.java
> <https://github.com/telefonicaid/fiware-sinfonier/pull/4#pullrequestreview-4885725>
> :
>
> > @@ -8,7 +8,7 @@
>  import com.google.gson.annotations.SerializedName;
>
>  public class Wire {
> -  private String xType;
> +  private String xtype;
>
> Why do you need rename it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/telefonicaid/fiware-sinfonier/pull/4#pullrequestreview-4885725>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFN0kIe_F9EdMM2_R-wF9wVxb0kBbWBPks5q1ix6gaJpZM4KazYD>
> .
>

2016-10-19 15:39 UTC, amatosc commented
it's ok but you can also use @SerializedName from Gson.

2016-10-20 10:34 UTC, demonodojo commented on sinfonier-web/app/models/module/ModuleVersion.java
> +			Logger.error(e.getMessage());
ok

2016-10-20 10:34 UTC, demonodojo commented on sinfonier-web/app/models/responses/Codes.java
>    CODE_400("NOOK", 400),
ok

2016-10-20 10:35 UTC, demonodojo commented on sinfonier-web/app/models/topology/json/serializers/TopologySerializer.java
> +    	try {
ok

2016-10-20 10:41 UTC, demonodojo commented on sinfonier-web/app/models/topology/Wire.java
> +  private String xtype;
Json serializer uses the property name to generate keys. This key must be lowercase.

2016-10-20 11:21 UTC, amatosc requested changes
Please check the test some of them are failed 

~ BasicTest...                                   PASSED     1s
~ tests/BaseTest...                              PASSED     0s
~ tests/models/module/ModuleTest...              FAILED  !  0s
~ tests/models/module/ModuleVersionTest...       PASSED     0s
~ tests/models/storm/ParamsValidatorTests...     PASSED     0s
~ tests/models/topology/TopologyTests...         PASSED     0s
~ ApplicationTest...                             PASSED     2s
~ tests/BaseTestFunctional...                    PASSED     0s
~ Application...                                 PASSED     5s

For checking execute play autotest

2016-10-20 11:50 UTC, demonodojo commented
A mi me aparecen los tests funcionando:

~ BasicTest...                                   PASSED     1s
~ tests/BaseTest...                              PASSED     0s
~ tests/models/module/ModuleTest...              PASSED     0s
~ tests/models/module/ModuleVersionTest...       PASSED     0s
~ tests/models/storm/ParamsValidatorTests...     PASSED     0s
~ tests/models/topology/TopologyTests...         PASSED     0s
~ ApplicationTest...                             PASSED     1s
~ tests/BaseTestFunctional...                    PASSED     0s
~ Application...                                 PASSED     4s

2016-10-20 12:25 UTC, fandrod approved these changes

2016-10-20 12:55 UTC, amatosc commented on sinfonier-web/app/models/topology/json/serializers/TopologySerializer.java
> +				throw new JsonException(e.getMessage(), e.getCause());
We always raise SinfonierExceptions. I will retrieve my  request change. Maybe this not important but it is the style used. @ivan11paths choice.

2016-10-20 12:56 UTC, amatosc approved these changes

2016-10-20 15:14 UTC, ivan11paths approved these changes

2016-10-20 15:14 UTC, demonodojo commented on sinfonier-web/app/models/topology/json/serializers/TopologySerializer.java
> +				throw new JsonException(e.getMessage(), e.getCause());
We are overriding a method that must implement an interface an cannot throw a SinfonierException

2016-10-20 15:15 UTC, merged