[Test] Create UnitTest and FuncionalTest. #19414.
telefonicaid/fiware-sinfonier pull request #8
Opened 2016-10-24 12:19 UTC by amatosc

2016-10-24 13:50 UTC, demonodojo approved these changes

2016-10-24 17:11 UTC, fandrod requested changes

2016-10-24 17:11 UTC, fandrod commented on sinfonier-web/test/tests/controllers/DiagnosisTest.java
> +    request = doLogin("test@test.com", "test");
Diagnosis test must be do without user logged in

2016-10-24 17:18 UTC, fandrod reviewed
Why some tests class have "doLogin" call on @BeforeClass and others on @Before? If it is possible do several test with same user session, I think it is better on @BeforeClass

2016-10-25 06:33 UTC, amatosc commented on sinfonier-web/test/tests/controllers/DiagnosisTest.java
> +    request = doLogin("test@test.com", "test");
It's right, I will change it now.

2016-10-25 06:34 UTC, amatosc commented
I did in this way because the request could be modified by the frameworks and it cause some troubles. Anyway I tried it in the first place but I had to change for fixing

2016-10-25 07:10 UTC, fandrod approved these changes

2016-10-25 07:55 UTC, ivan11paths requested changes

2016-10-25 07:55 UTC, ivan11paths commented on sinfonier-web/test/tests/controllers/ProfileSinfonierTest.java
> +    assertTrue(true);
This test isn't functional

2016-10-25 14:31 UTC, ivan11paths approved these changes

2016-10-25 14:32 UTC, merged